name: module3_task1

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

jobs:
  validate:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task1 && ./setup.sh
      - run: cd module3_task1 && make build
